
title: Shrdlite

email: peter.ljunglof@gu.se

description: > # this means to ignore newlines until "baseurl:"
  The Shrdlite project. Bla bla bla.

markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
